### ISSUE TITLE
missing sound file for Web Audio API Binaural module 

### ISSUE THREAD

**Issue by vberthiaume** [Ircam-RnD/binauralFIR#9]
The sound file is marked as missing here: https://ircam-rnd.github.io/binauralFIR/

**Comment by PyrApple** [comment]
Can't reproduce here. Marked as missing in the browser console or disabled audio tag? which browser?

**Comment by vberthiaume** [comment]
right, sorry! In internet explorer I see this: 

![capture](https://cloud.githubusercontent.com/assets/3721265/23623855/9b574e4e-0271-11e7-829c-dccec6785a8e.PNG)
 
and in chrome I see this:

![captur2e](https://cloud.githubusercontent.com/assets/3721265/23623891/ba2e78b0-0271-11e7-934a-89a17dd9bc77.PNG)

In chrome, I can press the play button and it seems as if the file is playing, but I get no sound.

**Comment by vberthiaume** [comment]
oh yeah, and I can download the file from chrome and play it locally. Really weird!

**Comment by PyrApple** [comment]
Could you load the page on Chrome with the View/Developer/Javascript Console enabled and post the logs?

**Comment by vberthiaume** [comment]
![captur3e](https://cloud.githubusercontent.com/assets/3721265/23624087/78c73460-0272-11e7-9b08-e6b1c915bebf.PNG)

**Comment by PyrApple** [comment]
latest chrome version?

**Comment by vberthiaume** [comment]
yes, latest version. Given the error message, I tried changing my sound card sampling rate to 44.1 kHz instead of 48 kHz, and now it works in chrome. Still same error in IE ;)

**Comment by PyrApple** [comment]
fixed audioContext creation for Safari, Web Audio API not supported on IE, see: http://caniuse.com/#feat=audio-api

**Comment by cbossut** [comment]
Still, in Chrome :

> Uncaught DOMException: Failed to set the 'buffer' property on 'ConvolverNode': The buffer sample rate of 44100 does not match the context rate of 48000 Hz.
>     at t.set (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:5238)
>     at t.value (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:3043)
>     at t.value (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:2233)
>     at https://ircam-rnd.github.io/binauralFIR/examples/:79:21

**Comment by cbossut** [comment]
And also

>  Uncaught DOMException: Failed to set the 'buffer' property on 'ConvolverNode': The buffer sample rate of 44100 does not match the context rate of 48000 Hz.
>     at t.set (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:5238)
>     at t.value (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:3043)
>     at t.value (https://ircam-rnd.github.io/binauralFIR/binaural-fir.min.js:1:2233)
>     at https://ircam-rnd.github.io/binauralFIR/examples/:79:21
